features <- read.table("~/UCI HAR Dataset/features.txt", quote="\"")
View(features)
colnames <- features$V2
colnames <- as.character(colnames)
subject_test <- read.table("~/UCI HAR Dataset/test/subject_test.txt", quote="\"")
View(subject_test)
X_test <- read.table("~/UCI HAR Dataset/test/X_test.txt", quote="\"")
View(X_test)
y_test <- read.table("~/UCI HAR Dataset/test/y_test.txt", quote="\"")
View(y_test)
subject_train <- read.table("~/UCI HAR Dataset/train/subject_train.txt", quote="\"")
View(subject_train)
X_train <- read.table("~/UCI HAR Dataset/train/X_train.txt", quote="\"")
View(X_train)
y_train <- read.table("~/UCI HAR Dataset/train/y_train.txt", quote="\"")
View(y_train)
subject <- rbind(subject_test, subject_train)
features <- read.table("~/UCI HAR Dataset/features.txt", quote="\"")
View(features)
subject <- rbind(subject_test, subject_train)
X <- rbind(X_test, X_train)
y <- rbind(y_test, y_train)
View(X)
colnames(X) <- features$V2
View(X)
id <- 1:10299
subject <- cbind(id=id, subject)
X <- cbind(id=id, X)
y <- cbind(id=id, y)
colnames(subject) <- c("id", "subject")
colnames(y) <- c("id", "activity")
View(y)
class(y$activity)
y$activity <- as.integer(y$activity)
class(y$activity)
y$activity <- gsub(5, "standing", y$activity)
y$activity <- gsub(1, "walking", y$activity)
y$activity <- gsub(2, "walking_upsatirs", y$activity)
y$activity <- gsub(3, "walking_downstairs", y$activity)
y$activity <- gsub(4, "sitting", y$activity)
y$activity <- gsub(6, "laying", y$activity)
View(y)
y$activity <- as.factor(y$activity)
com <- merge(y, subject)
View(com)
com <- merge(com, X)
View(com)
com$subject <- as.factor(com$subject)
colnames(com)
splitNames = strsplit(names(com), "-")
colnames(com)
class(splitNames)
splitNames <- as.array(splitNames)
head(splitNames)
remove <- grep("meanFreq", names(com))
length(grep("std", names(com)))
reqcom <- com[, subsettablelist]
subsettablelist <- subsettablelist [!c(1, 2, 3)]
subsettablelist <- c(grep("std", names(com)), grep("mean", names(com)))
subsettablelist <- subsettablelist [!subsettablelist %in% remove]
subsettablelist <- c(1, 2, 3, subsettablelist)
sort(subsettablelist)
reqcom <- com[, subsettablelist]
View(reqcom)
write.csv(reqcom, "~/Getting_and_Cleaning_Data/TidyData1.csv")
yo <- lapply(split(reqcom[[5]], list(f1,f2)), mean)
naam <- names(yo)
yo2 <- data.frame(naam)
for(x in 4:69){
        yo <- lapply(split(reqcom[[x]], list(f1,f2)), mean)
        for(y in 1:180){
                yo2[y, (x-2)] <- as.numeric(yo[y])
        }
}
colnaam <- c("observation", as.character(names(reqcom[4:69])))
colnaam
names(yo2) <- colnaam
View(yo2)
yo1 <- yo2[2:67]
yo3 <- cbind(Actions = rep(c("Laying", "Sitting", "Standing", "Walking", "Walking_downstairs", "Walking_downstairs"), times = 30), Subject = rep(1:30, each = 6), yo1)
View(yo3)
write.csv(yo2, "~/Getting_and_Cleaning_Data/Req.csv")